name: Publish Package

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'package.json'
      - '.github/workflows/publish.yml'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Get version from package.json
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1

      - name: Generate version
        id: generate-version
        run: |
          CURRENT_VERSION=${{ steps.package-version.outputs.current-version }}
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          NEW_VERSION="${CURRENT_VERSION}-${TIMESTAMP}"
          echo "new_version=${NEW_VERSION}" >> $GITHUB_OUTPUT

      - name: Update version in package.json
        run: |
          NEW_VERSION=${{ steps.generate-version.outputs.new_version }}
          npm version $NEW_VERSION --no-git-tag-version

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: Publish to npm
        run: pnpm publish --no-git-checks --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create Git tag
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag v${{ steps.generate-version.outputs.new_version }}
          git push origin v${{ steps.generate-version.outputs.new_version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
